apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: docs-yirrasystems
  namespace: drone-store
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`docs.yirrasystems.com`)
    priority: 50
    services:
    - name: docs
      port: 4000
      namespace: drone-store


