apiVersion: v1
kind: Service
metadata:
  name: contact-api
  namespace: fabrilab
  labels:
    app: contact-api
spec:
  selector:
    app: contact-api
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
