apiVersion: v1
kind: Secret
metadata:
  name: contact-api-secrets
  namespace: fabrilab
type: Opaque
data:
  # Base64 encoded SMTP credentials for Gmail
  smtp_host: c210cC5nbWFpbC5jb20=
  smtp_port: NDY1
  smtp_user: amFtZXNAZmFicmlsYWIuY29tLmF1
  smtp_pass: cnVpeiBmZGRoIHpveXAgemNrYw==
