apiVersion: v1
kind: Service
metadata:
  name: fabrilab
  namespace: fabrilab
  labels:
    app: fabrilab
spec:
  selector:
    app: fabrilab
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
