apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projects-svc-host
  namespace: drone-store
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: projects.staggingapp.yirrasystems.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: projects-svc
                port:
                  number: 8080
