apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-frontend-prod
  namespace: drone-store
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: app.yirrasystems.com
      http:
        paths:
          - path: /api/admin/projects
            pathType: Prefix
            backend:
              service:
                name: projects-svc
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
          - path: /chat/ws
            pathType: Prefix
            backend:
              service:
                name: ai-chat-service
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 3001
